sudo: required
services:
  - docker

before_install:
  - docker build -t cecnic1989/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cecnic1989/react-test npm test

after_success:
  - docker build -t cecnic1989/multi-client ./client
  - docker build -t cecnic1989/multi-nginx ./nginx
  - docker build -t cecnic1989/multi-server ./server
  - docker built -t cecnic1989/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push cecnic1989/multi-client
  - docker push cecnic1989/multi-nginx
  - docker push cecnic1989/multi-server
  - docker push cecnic1989/multi-worker
